### ISSUE TITLE
Transformer step (with or without 'custom') fails

### ISSUE THREAD

**Issue by sjr-db** [mlflow/recipes-examples#29]
Running the databricks classification code as is yields the following stacktrace, same if the transformer step is removed from the recipe.yaml file: 
```
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-31a73d6c-afc2-4264-a090-c7698df1f926/lib/python3.9/site-packages/mlflow/recipes/step.py", line 139, in run
    self.step_card = self._run(output_directory=output_directory)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-31a73d6c-afc2-4264-a090-c7698df1f926/lib/python3.9/site-packages/mlflow/recipes/steps/transform.py", line 105, in _run
    validate_classification_config(self.task, self.positive_class, train_df, self.target_col)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-31a73d6c-afc2-4264-a090-c7698df1f926/lib/python3.9/site-packages/mlflow/recipes/utils/step.py", line 182, in validate_classification_config
    raise MlflowException(
mlflow.exceptions.MlflowException: `positive_class` must be specified for classification/v1 recipes. 
```

**Comment by sunishsheth2009** [comment]
Thank you so much for reporting this issue. We recently merged a fix in [mlflow master](https://github.com/mlflow/mlflow/pull/7626) to resolve this issue. 
Let me know if that fixes the issue for you.

**Comment by paprocki-r** [comment]
The error still occurs

**Comment by sunishsheth2009** [comment]
The PR above was merged on December 29th and the latest release was released on 25th December. We do plan to do another release soon but until then can we try installing MLflow from master and see if that solves the problem? Thank you :)

**Comment by sjr-db** [comment]
Just added as a new repo to databricks, ran the classification example and hit the same error at the r.run("transform") cell. 

"mlflow.exceptions.MlflowException: `positive_class` must be specified for classification/v1 recipes." 

Looking at the yaml, that value is set to 1, I tried it as "1" but the same error occurred.

**Comment by sunishsheth2009** [comment]
The new repo of mlflow/recipes-examples unfortunately won't solve this bug. We need to install [mlflow](https://github.com/mlflow/mlflow/) from master. We could add another line here after [this](https://github.com/mlflow/recipes-examples/blob/main/classification/notebooks/databricks.py#L12) as `%pip install git+https://github.com/mlflow/mlflow@master`  and get the latest version of mlflow installed or install the latest as a pip library in Databricks cluster. Let me know if you have any other questions :)
